version: '2'
services:
    jhipster-elasticsearch:
        image: jhipster/jhipster-elasticsearch
        ports:
            - 9200:9200
            - 9300:9300
        ulimits:
            memlock:
                soft: 68719476736
                hard: 68719476736
        # Uncomment this section to have elasticsearch data persisted to a volume
        #volumes:
        #   - ./log-data:/usr/share/elasticsearch/data
    jhipster-logstash:
        image: jhipster/jhipster-logstash
        command: logstash -f /conf/logstash.conf
        ports:
            - 5000:5000/udp
        # Uncomment this section and add a logstash.conf file in log-conf/
        # to have logstash config loaded from a volume
        #volumes:
        #    - ./log-conf/:/conf
    jhipster-console:
        image: jhipster/jhipster-console
        ports:
            - 5601:5601
        #environment:
        #    - ELASTICSEARCH_URL=http://jhipster-elasticsearch:9200    
        # Uncomment this section to have kibana JSON files loaded from a volume
        #volumes:
        #    - ./dashboards:/tmp/dashboards
    jhipster-alerter:
        image: jhipster/jhipster-alerter
        #volumes:
        #    - ./jhipster-alerter/rules/:/opt/elastalert/rules/
        #    - ./alerts/config.yaml:/opt/elastalert/config.yaml
